include:
  - path: ./compose/docker-networks.yml

# Конфигурация postgresql
services:
  service-postgresql.black-hole.team:
    image: postgres:17
    restart: always
    networks:
      - blackHoleNetwork
    environment:
      POSTGRES_USER: asky
      POSTGRES_PASSWORD: changeit
      POSTGRES_DB: asky
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5430:5432
    volumes:
      - ./volumes/service-postgresql.black-hole.team:/var/lib/postgresql/data/pgdata
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5

# Волумы
volumes:
  service-postgresql.black-hole.team:
    driver: local