-- Таблица чатов (chat)
CREATE TABLE chat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    channel_id VARCHAR NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    banned_at TIMESTAMP,
    PRIMARY KEY (id, channel_id)
);

-- Таблица хабов (hub)
CREATE TABLE hub (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    channel_id VARCHAR NOT NULL,
    name VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (id, channel_id)
);

-- Таблица обращений (ticket)
CREATE TABLE ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject VARCHAR(512) NOT NULL,
    status VARCHAR NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    chat_id BIGINT NOT NULL,
    chat_channel_id VARCHAR NOT NULL,
    FOREIGN KEY (chat_id, chat_channel_id) REFERENCES chat(id, channel_id)
);

-- Индекс для статуса обращений
CREATE INDEX idx_ticket_status ON ticket (status);

-- Таблица связей обращений с темами (ticket_hub_topic)
CREATE TABLE hub_topic (
    id BIGINT NOT NULL,
    hub_id BIGINT NOT NULL,
    hub_channel_id VARCHAR NOT NULL,
    ticket_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (ticket_id) REFERENCES ticket (id),
    FOREIGN KEY (hub_id, hub_channel_id) REFERENCES hub (id, channel_id)
);

CREATE INDEX hub_topic_ticket_id ON hub_topic (ticket_id);
CREATE INDEX hub_topic_hub_id ON hub_topic (hub_id);
CREATE INDEX hub_topic_hub_channel_id ON hub_topic (hub_channel_id);

